name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main
# --- IGNORE ---
jobs:
  deploy:
    runs-on: ubuntu-latest
#code
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/node-app
            git pull origin main || git clone https://github.com/ManinderMander/my-node-app.git ~/node-app
            npm install
            pm2 restart all || pm2 start server.js --name node-app
# --- IGNORE ---
#  End of code
# --- IGNORE ---